server:  
  port: 8080
 
circuit-breaker:
  sliding-windows-size: ${CB_SLIDING_WINDOWS_SIZE}
  number-calls-in-half-open-state: ${CB_CALLS_HALF_OPEN_STATE}
  failure-rate-threshold: ${CB_FAILURE_RATE_THRESHOLD}
  wait-duration-open-state: ${CB_WAIT_DURATION_OPEN_STATE}


spring:
  application:
    name: api-gateway
  zipkin:
    base-url: ${ZIPKIN_URL}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        register: false
        registerHealthCheck: false
      config:
        # To avoid consul from requesting configurations
        enabled: false
    circuitbreaker:
      resilience4j:
        enabled: true
